accordappmain/accord/api/urls.py
from django.urls import path
from . import views
from .views import Userlogin

urlpatterns = [
    path('', views.getRouts),
    path('lobbys/', views.getLobbys),
    path('users/', views.getUsers),
    path('lobbys/<str:pk>/', views.getLobby),
    path('login/', Userlogin.as_view(), ),

]

accordappmain/accord/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('', views.mainmenu, name='menu'),

    path('home/', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('tasks/', views.tasks, name='tasks'),
    path('lobby/<str:pk>/', views.lobby, name='lobby'),
    path('user_profile/<str:pk>', views.user_profile, name='user-profile'),
    path('order_list', views.order_list, name='order-list'),
    path('update_user/', views.update_user, name="update-user"),
    path('home/update_order/<str:pk>', views.update_order, name="update-order"),

    path('topics/', views.topics, name='topics'),
    path('pages/', views.pages, name='pages'),
    path('activity/', views.activity, name='activity'),
    path('create_lobby/', views.create_lobby, name='create-lobby'),
    path('create_order/', views.create_order, name='create-order'),
    path('create_order_customer/', views.create_order_customer, name='create-order-customer'),
    path('create_product/', views.create_product, name='create-product'),
    path('create_task/', views.create_task, name='create-task'),
    path('update_lobby/<str:pk>/', views.update_lobby, name='update-lobby'),
    path('delete_lobby/<str:pk>/', views.deleteLobby, name='delete-lobby'),
    path('delete_post/<str:pk>/', views.deletePost, name='delete-post'),

    path('order_success/', views.success, name='success'),
    path('welcometoseikai/', views.welcome, name='welcome'),


    path('coinshophome', views.coinShopHome, name='coinshophome'),
]

accordappmain/accord/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=20, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Lobby(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lobby = models.ForeignKey(Lobby, on_delete=models.CASCADE)
    post = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.post[0:10]


class Pages(models.Model):
    page_name = models.CharField(max_length=100, null=True, blank=True)
    url = models.CharField(max_length=200, null=True, blank=True)


class Product(models.Model):
    product_name = models.CharField(max_length=200, null=True, blank=False)
    product_details = models.TextField(null=True, blank=False)
    full_sleeve_price = models.IntegerField(null=True, blank=False)
    half_sleeve_price = models.IntegerField(null=True, blank=False)
    preorder = models.IntegerField(null=True, blank=True)
    product_id = models.CharField(max_length=200, null=True, blank=True)
    product_type = models.CharField(max_length=200, null=True, blank=False)
    available = models.CharField(max_length=200, null=True, blank=False)
    avatar = models.ImageField(null=True, blank=False, default='jersey-avatar.png')

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='product')
    created_date = models.DateTimeField(null=True, blank=True)


class Order(models.Model):
    PAYMENT_CHOICES = [
        (None, 'Select Bkash/Nagad number you paid to'),
        ('01797407811', '01797407811'),
        ('01960008530', '01960008530'),
        ('01309956343', '01309956343'),
        ('01609212434', '01609212434'),
        ('01941171107', '01941171107')
    ]
    order_id = models.CharField(max_length=200, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=False, related_name='product')

    customer_name = models.CharField(max_length=200, null=True, blank=False)
    customer_contactnumber = models.CharField(max_length=200, null=True, blank=False)
    customer_email = models.CharField(max_length=200, null=True, blank=True)
    customer_address = models.TextField(null=True, blank=False)
    delivery_address = models.TextField(null=True, blank=False)
    customer_fb = models.CharField(max_length=200, null=True, blank=True)
    customer_discord = models.CharField(max_length=200, null=True, blank=True)

    quantity = models.IntegerField(null=True, blank=True)
    size = models.CharField(max_length=200, null=True, blank=True)
    custom_name = models.CharField(max_length=200, null=True, blank=True)
    custom_number = models.CharField(max_length=20, null=True, blank=True)
    total_price = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, null=True, blank=True, default='PENDING')
    paid = models.IntegerField(null=True, blank=False)
    # money_received_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='received_by')
    paid_to_number = models.CharField(max_length=11, choices=PAYMENT_CHOICES, default='NULL', blank=False)

    bkash_number = models.CharField(max_length=200, null=True, blank=False)
    bkash_txn_id = models.CharField(max_length=200, null=True, blank=False)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='order')
    created_date = models.DateTimeField(null=True, blank=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='updated_by_order')
    updated_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.product


class Order_Product(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=False, related_name='order_product')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=False, related_name='product_order')

    quantity = models.IntegerField(null=True, blank=False)
    size = models.CharField(max_length=200, null=True, blank=True)
    sleeve = models.CharField(max_length=200, null=True, blank=True, default='half')


class Tasks(models.Model):
    task_id = models.CharField(max_length=200, null=True, blank=True)
    task_details = models.TextField(null=True)
    assign_date = models.DateField(auto_now_add=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assigned')
    deadline_date = models.DateField()
    completed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='complete')
    remarks = models.TextField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='task')
    created_date = models.DateTimeField(null=True, blank=True)

accordappmain/accord/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Select
from django_select2.forms import ModelSelect2Widget

from .models import *
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'password1', 'password2']


class LobbyForm(ModelForm):
    class Meta:
        model = Lobby
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'username', 'email', 'name', 'bio']


class OrderForm(forms.ModelForm):
    # PAYMENT_CHOICES = [
    #     ('', 'Select Bkash/Nagad number you paid to'),
    #     (7, '01797407811'),
    #     (4, '01960008530'),
    #     (3, '01309956343'),
    #     (5, '01609212434'),
    #     (6, '01941171107')
    # ]
    # money_received_by = forms.IntegerField(label='Enter Payment to number', widget=forms.Select(choices=PAYMENT_CHOICES))

    class Meta:
        model = Order
        # fields = ['customer_name', 'customer_contactnumber', 'customer_address', 'quantity', 'total_price']
        fields = '__all__'
        exclude = ['created_by', 'created_date', 'updated_by', 'updated_date']


class OrderFormRetrieve(forms.ModelForm):
    class Meta:
        model = Order
        # fields = ['customer_name', 'customer_contactnumber', 'customer_address', 'quantity', 'total_price']
        fields = '__all__'
        exclude = ['created_by', 'created_date', 'updated_by', 'updated_date', 'total_price', 'status', 'quantity',
                   'size']


class OrderFormPOST(forms.ModelForm):
    class Meta:
        model = Order
        # fields = ['customer_name', 'customer_contactnumber', 'customer_address', 'quantity', 'total_price']
        fields = '__all__'
        exclude = ['created_by', 'created_date', 'updated_by', 'updated_date', 'product', 'order_id']


class ProductForm(ModelForm):
    product_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter Product Name'}))
    product_details = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter Product Details'}))

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['created_by', 'created_date']


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(ModelForm):
    task_details = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter Task Details'}))
    remarks = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter Remarks'}))

    class Meta:
        model = Tasks
        fields = '__all__'
        exclude = ['created_by', 'created_date', 'assign_date', 'assigned_to', 'completed_by']
        widgets = {
            'deadline_date': DateInput(),
        }


class OrderProductForm(ModelForm):
    class Meta:
        model = Order_Product
        fields = ['quantity', 'size', 'sleeve']

accordappmain/accord/api/views.py
from django.contrib.auth import login, authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from accord.models import Lobby, User
from rest_framework.views import APIView

from .serializers import *

@api_view(['GET'])
def getRouts(request):
    routs = [
        'GET /api',
        'GET /api/lobbys',
        'GET /api/lobbys/:id'
    ]

    return Response(routs)


@api_view(['GET'])
def getLobbys(request):
    lobbys = Lobby.objects.all()
    serializer = LobbySerializer(lobbys, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getLobby(request, pk):
    lobby = Lobby.objects.get(id=pk)
    serializer = LobbySerializer(lobby, many=False)
    return Response(serializer.data)


@api_view(['GET'])
def getUsers(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)

# @csrf_exempt
class Userlogin(APIView):
    permission_classes = (AllowAny,)
    serializer_class = LoginSerializer


    def get(self, request):
        user = User.objects.all()
        serializer = LobbySerializer(user, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        if serializer.is_valid():
            user = User.objects.get(email=request.data['email'])
            return Response(user.username, status=200)
        else:
            return Response(status=400)


# @api_view(['POST'])
# def userlogin(request):
#     serializer = LoginSerializer(data=request.data)
#     print(serializer)
#     # user = authenticate(request, serializer=serializer)
#     # print(user)
#     # print(serializer.is_valid())
#     if serializer.is_valid():
#         print('valid')
#         # user = serializer.validated_data['user']
#         # login(request, user)
#         return Response(serializer.data)
#     else:
#         return Response('bhai hoy nai')

    # permission_classes = (AllowAny,)
    # serilaizer = LoginSerializer

accordappmain/accord/templates/accord/coinshophome.html
{% extends 'main.html' %}

{% block content %}

    <style>
        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            background: #ffcfa5;
            border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #ed6a4c;
            border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #555;
        }

        .page-label {
            padding-bottom: 10rem;
        }

        .btn-img {
            width: 30rem;
            box-shadow: 0px 5px 15px 2px #888888;
            border-radius: 20px;
            padding: 50px;
            background-color: #ed6a4c;
            transition: all .2s ease-in-out;
        }

        .btn-img:hover {
            transform: scale(1.1);
        }

        .graph, .expense, .fund, .recent {
            box-shadow: 0px 5px 15px 2px #888888;
            border-radius: 20px;
            padding: 2rem 3rem;
            margin: 2rem;
            transition: all .2s ease-in-out;
        }

        .graph:hover, .expense:hover, .fund:hover, .recent:hover {
            transform: scale(1.05);
        }

        .expense {
            height: 200px;
        }

        th {
        {#border-left: 1px solid black;#}{#border-right: 1px solid black;#}{#border-bottom: 1px solid black;#} border-radius: 5px;
            padding: 0.5rem;
            width: auto;
            color: white;
            position: sticky;
            top: 0;
            text-align: center;
        {#background-color: #fc4b0b;#} background-color: #ED6A4C;
        }

        body, html {
            height: 100%;
            text-align: center;
        }

        body {
            background-color: antiquewhite;
        }


        @media (min-width: 1200px) {
            .container {
                width: 100%;
            }
        }

        @media (min-width: 992px) {
            .container {
                width: 100%;
            }
        }

        @media (min-width: 768px) {
            .container {
                width: 100%;
            }
        }

        {#---------< chart css >----------#}

        #animations-example-3 {
            height: 450px;
            max-width: 500px;
        {#margin: 0 auto;#}
        }

        #animations-example-3 tbody {
            overflow-y: hidden; /* remove this to see how it works */
        }

        #animations-example-3 tbody th {
            background-color: #ed6a4c;
            z-index: 1;
        }

        #animations-example-3 tbody td {
            animation: moving-bars 4s linear;
            background-color: #ff6e40;
        }

        #animations-example-3 td {
            background-image: linear-gradient(
                    45deg,
                    #fc4b0b,
                    #f7612e,
                    #fc7d53,
                    #ff9775,
                    #fcc3b0,
                    #fcd6c9
            );
            background-size: 600%;
            animation: gradient-animation 3s linear infinite alternate;
        }

        @keyframes gradient-animation {
            0% {
                background-position: 0%;
            }
            100% {
                background-position: 100%;
            }
        }


        @keyframes moving-bars {
            0% {
                transform: translateY(100%);
            }
            15% {
                transform: translateY(0);
            }
        }

        .data {
            color: #e1f6fb;
        }


    </style>



    <div class="container" style="max-height: 600px">
        <div class="row">
            <div class="col-lg-2 pages">
                {% include 'accord/topics_component.html' %}
            </div>
            <div class="col-lg-7">
                <div class="row">
                    <div class="col-lg-auto graph">
                        {#                        <img src="https://picsum.photos/3840/2160/?random"/>#}
                        <table id="animations-example-3"
                               class="charts-css column show-labels data-spacing-5 show-primary-axis">
                            <caption> Animation Example #3</caption>
                            <thead>
                            <tr>
                                <th scope="col"> Year</th>
                                <th scope="col"> Progress</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row"> 2016</th>
                                <td style="--size:.3;"><span class="data"> 30 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2017</th>
                                <td style="--size:0.8;"><span class="data"> 80 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2018</th>
                                <td style="--size:0.7;"><span class="data"> 70 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2019</th>
                                <td style="--size:0.8;"><span class="data"> 80 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2020</th>
                                <td style="--size:0.6;"><span class="data"> 60 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2021</th>
                                <td style="--size:.95;"><span class="data"> 95 </span></td>
                            </tr>
                            <tr>
                                <th scope="row"> 2022</th>
                                <td style="--size:0.2;"><span class="data"> 20 </span></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-auto expense">
                        <div class="expense-div" style="max-height:170px; overflow: auto">
                            <table class="table table-hover table-bordered">
                                <tr>
                                    <th>Company</th>
                                    <th>Contact</th>
                                    <th>Country</th>
                                </tr>
                                <tr>
                                    <td>Alfreds Futterkiste</td>
                                    <td>Maria Anders</td>
                                    <td>Germany</td>
                                </tr>
                                <tr>
                                    <td>Centro comercial Moctezuma</td>
                                    <td>Francisco Chang</td>
                                    <td>Mexico</td>
                                </tr>
                                <tr>
                                    <td>Ernst Handel</td>
                                    <td>Roland Mendel</td>
                                    <td>Austria</td>
                                </tr>
                                <tr>
                                    <td>Island Trading</td>
                                    <td>Helen Bennett</td>
                                    <td>UK</td>
                                </tr>
                                <tr>
                                    <td>Laughing Bacchus Winecellars</td>
                                    <td>Yoshi Tannamuri</td>
                                    <td>Canada</td>
                                </tr>
                                <tr>
                                    <td>Magazzini Alimentari Riuniti</td>
                                    <td>Giovanni Rovelli</td>
                                    <td>Italy</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="row fund">
                    Funds
                </div>
                <div class="row recent">
                    Recent Sells
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>


{% endblock content %}

accordappmain/accord/templates/accord/create_update_lobby.html
{% extends 'main.html' %}

{% block content %}

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home'%}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Order</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}

            <div class="form__group">
              <label>Customer Name</label>
                {{form.name}}
{#              <input required type="text" value="{{lobby.topic.name}}" name="topic" list="topic-list">#}
{#              <datalist id="topic-list">#}
{#                <select id="lobby-topic">#}
{#                  {% for topic in topics %}#}
{#                  <option value="{{topic.name}}">{{topic.name}}</option>#}
{#                  {% endfor %}#}
{#                </select>#}

{#              </datalist>#}
<!--              <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />-->
            </div>
            <div class="form__group">
              <label>Customer Mobile</label>
              {{form.name}}
<!--              <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />-->
            </div>
            <div class="form__group">
              <label>Description</label>
              {{form.description}}
<!--              <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />-->
            </div>

<!--            <div class="form__group">-->
<!--              <label for="room_topic">Topic</label>-->
<!--              <input required type="text" name="topic" id="room_topic" list="topic-list" />-->
<!--              <datalist id="topic-list">-->
<!--                <select id="room_topic">-->
<!--                  <option value="">Select your topic</option>-->
<!--                  <option value="Python">Python</option>-->
<!--                  <option value="Django">Django</option>-->
<!--                </select>-->
<!--              </datalist>-->

<!--            </div>-->



            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

accordappmain/accord/templates/accord/delete_old.html
{%extends 'main.html'%}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    <input type="submit" value="Confirm">
</form>

{% endblock content%}

accordappmain/accord/templates/accord/login_register_old.html
{% extends 'main.html' %}

{% block content %}

    {% if page == 'login' %}
    <div>
        <form method="POST" action="">
            {%csrf_token%}
            <label>Username: </label>
            <input type="text" name="username" placeholder="Enter Username">

            <label>Password: </label>
            <input type="password" name="password" placeholder="Enter Password">

            <br><input type="submit" value="Login">
        </form>

        <p>Don't have an account?</p>
        <a href="{% url 'signup'%}">Sign Up!</a>
    </div>
    {% else %}
    <div>
        <form method="POST" action="">
            {%csrf_token%}
            {{form.as_p}}
            <br><input type="submit" value="Sign Up">
        </form>

        <p>Already have an account?</p>
        <a href="{% url 'login'%}">Login</a>
    </div>
    {% endif %}
{% endblock content %}

accordappmain/accord/templates/accord/pages.html
{% extends 'main.html' %}

{% block content %}

    <style>
        .topics__list li a {
            display: flex;
            justify-content: center;
            margin-bottom: 3rem;
            font-weight: 700;
            color: var(--color-light-gray);
            transition: all 0.3s ease-in-out;
            color: #ffcfa5;
            font-size: 25px;
            text-align: justify-all
        }
    </style>

    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Browse Pages</h3>
                    </div>
                </div>

                <div class="topics-page layout__body">
                    {#                    <form action="" method="GET" class="header__search">#}
                    {#                        <label>#}
                    {#                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"#}
                    {#                                 viewBox="0 0 32 32">#}
                    {#                                <title>search</title>#}
                    {#                                <path#}
                    {#                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">#}
                    {#                                </path>#}
                    {#                            </svg>#}
                    {#                            <input name="q" placeholder="Search for pages"/>#}
                    {#                        </label>#}
                    {#                    </form>#}

                    <ul class="topics__list">
                        {#          <li>#}
                        {#            <a href="{% url 'pages' %}" class="active">All <span>{{pages.count}}</span></a>#}
                        {#          </li>#}
                        {% for page in pages %}
                            <li>
                                {#            <a href="{% url 'home' %}?q={{page.page_name}}">{{ page.page_name }} <span>{{page.lobby_set.all.count}}</span></a>#}
                                <a href="{{ page.url }}">{{ page.page_name }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}